---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-rest-blue
spec:
  selector:
    app: spring-boot-rest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot-rest-green
spec:
  selector:
    app: spring-boot-rest
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080