apiVersion: v1
kind: Service
metadata:
  name: spring-boot-rest
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 30081
  selector:
    app: spring-boot-rest
  type: NodePort
