---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: bxcr-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: spring-boot-rest
spec:
  gateways:
  - istio-system/bxcr-gateway
  hosts:
  - '*'
  http:
  - name: primary
    match:
    - uri:
        prefix: /default/spring-boot-rest/
    rewrite:
      uri: /
    route:
    - destination:
        host: spring-boot-rest-stable
      weight: 100
    - destination:
        host: spring-boot-rest-canary
      weight: 0
