apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: spring-boot-rest
spec:
  replicas: 10
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: spring-boot-rest
      version: v1
  template:
    metadata:
      labels:
        app: spring-boot-rest
        version: v1
    spec:
      containers:
      - name: spring-boot-rest
        image: smartkuk/spring-boot-rest:green
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    canary:
      maxSurge: "25%"
      maxUnavailable: 0
      steps:
      - setWeight: 10
      - pause: {}
---
kind: Service
apiVersion: v1
metadata:
  name: spring-boot-rest
spec:
  selector:
    app: spring-boot-rest
    version: v1
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30081
  type: NodePort
